version: '3.1'

services:
  db:
    image: mysql
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: antville!
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass antville! --port 6379
    hostname: redis
    ports:
      - 6379:6379
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
