version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: valueTalk!
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
