// Generated by https://quicktype.io

export interface KoreaStockList {
  trdDd: string;
  mktEndTm: string;
  isuLists: KoreaStock[];
}

export interface KoreaStock {
  isuSrtCd: string;
  isuKorNm: string;
  isuKorAbbr: string;
}
