name: deploy develop branch to ec2

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull & deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/antville-app-server
            git pull
            docker stop app
            docker rm app
            docker build --rm=true -t server .
            docker-compose up -d
